### ISSUE TITLE
Caps-Lock indicator

### ISSUE THREAD

**Issue by Cognosis87** [Rasnar/qmk-gmmk-pro-key-mapping#1]
Loving the build. Is there a way to enable the Caps-lock indicator?

**Comment by Rasnar** [comment]
It's possible to add a caps-lock indicator (e.g. setting the RGB to a specific color) using custom functions in QMK and rebuilding the code: 
https://docs.qmk.fm/#/custom_quantum_functions?id=led-control 

In my case, I don't use much the RGB on my GMMK pro, so I didn't want to add this feature.
